name: Deploy All Environments

on:
  workflow_dispatch:
    inputs:
      import_enabled:
        required: false
        type: boolean
        default: false
      action:
        description: 'Terraform action to perform (apply or destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  approve-all:
    name: Manual Approval for All Environments
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval for All Landing Zones
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Manual approval for ${{ github.event.inputs.action || 'apply' }} on all Landing Zones"
          issue-body: |
            **Environments**: Platform, Corp, and Online Landing Zones
            **Action**: ${{ github.event.inputs.action || 'apply' }}
            **Triggered by**: @${{ github.actor }}
            **Workflow**: ${{ github.workflow }}
            **Import Enabled**: ${{ github.event.inputs.import_enabled || 'false' }}
            
            Please review and approve the deployment for all Landing Zones.
            
            This will ${{ github.event.inputs.action || 'apply' }} the following environments in sequence:
            1. Platform Landing Zone
            2. Corp Landing Zone  
            3. Online Landing Zone

  platform:
    name: Platform LZ
    needs: [approve-all]
    uses: ./.github/workflows/terraform-workflow.yaml
    with:
      environment: platform
      action: ${{ github.event.inputs.action || 'apply' }}
      import_enabled: ${{ github.event.inputs.import_enabled || false }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
       # Backend SPN (for terraform backend)
      ARM_BACKEND_CLIENT_ID: ${{ secrets.ARM_BACKEND_CLIENT_ID }}
      ARM_BACKEND_CLIENT_SECRET: ${{ secrets.ARM_BACKEND_CLIENT_SECRET }}
      ARM_BACKEND_TENANT_ID: ${{ secrets.ARM_BACKEND_TENANT_ID }}
      ARM_BACKEND_SUBSCRIPTION_ID: ${{ secrets.ARM_BACKEND_SUBSCRIPTION_ID }}

  corp:
    name: Corp LZ
    needs: [approve-all]
    uses: ./.github/workflows/terraform-workflow.yaml
    with:
      environment: corp
      action: ${{ github.event.inputs.action || 'apply' }}
      import_enabled: ${{ github.event.inputs.import_enabled || false }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
       # Backend SPN (for terraform backend)
      ARM_BACKEND_CLIENT_ID: ${{ secrets.ARM_BACKEND_CLIENT_ID }}
      ARM_BACKEND_CLIENT_SECRET: ${{ secrets.ARM_BACKEND_CLIENT_SECRET }}
      ARM_BACKEND_TENANT_ID: ${{ secrets.ARM_BACKEND_TENANT_ID }}
      ARM_BACKEND_SUBSCRIPTION_ID: ${{ secrets.ARM_BACKEND_SUBSCRIPTION_ID }}

  online:
    name: Online LZ
    needs: [approve-all]
    uses: ./.github/workflows/terraform-workflow.yaml
    with:
      environment: online
      action: ${{ github.event.inputs.action || 'apply' }}
      import_enabled: ${{ github.event.inputs.import_enabled || false }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      # Backend SPN (for terraform backend)
      ARM_BACKEND_CLIENT_ID: ${{ secrets.ARM_BACKEND_CLIENT_ID }}
      ARM_BACKEND_CLIENT_SECRET: ${{ secrets.ARM_BACKEND_CLIENT_SECRET }}
      ARM_BACKEND_TENANT_ID: ${{ secrets.ARM_BACKEND_TENANT_ID }}
      ARM_BACKEND_SUBSCRIPTION_ID: ${{ secrets.ARM_BACKEND_SUBSCRIPTION_ID }}

