name: Deploy Selected Environment

on:
  workflow_dispatch:
    inputs:
      import_enabled:
        required: false
        type: boolean
        default: false
      action:
        description: 'Terraform action to perform (apply or destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      environment:
        description: 'Terraform environment to deploy'
        required: true
        default: 'platform'
        type: choice
        options:
          - platform
          - corp
          - online

jobs:

  deploy:
    name: Deploy ${{ github.event.inputs.environment || 'platform' }} LZ
    uses: ./.github/workflows/terraform-workflow.yaml
    with:
      environment: ${{ github.event.inputs.environment || 'platform' }}
      action: ${{ github.event.inputs.action || 'apply' }}
      import_enabled: ${{ github.event.inputs.import_enabled || false }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
       # Backend SPN (for terraform backend)
      ARM_BACKEND_CLIENT_ID: ${{ secrets.ARM_BACKEND_CLIENT_ID }}
      ARM_BACKEND_CLIENT_SECRET: ${{ secrets.ARM_BACKEND_CLIENT_SECRET }}
      ARM_BACKEND_TENANT_ID: ${{ secrets.ARM_BACKEND_TENANT_ID }}
      ARM_BACKEND_SUBSCRIPTION_ID: ${{ secrets.ARM_BACKEND_SUBSCRIPTION_ID }}

